apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
  name: rng
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  sessionAffinity: None
  type: ClusterIP
