apiVersion: v1
kind: Service
metadata:
  labels:
    app: adder
  name: adder
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adder
  sessionAffinity: None
  type: ClusterIP