apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: source
  name: source
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: source
    spec:
      containers:
      - image: newler55/source
        imagePullPolicy: IfNotPresent
        name: source
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30