apiVersion: v1
kind: Service
metadata:
  labels:
    app: source
  name: source
  namespace: default
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: source
  sessionAffinity: None
  type: ClusterIP