apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: thakorn09/server:latest
        imagePullPolicy: Always
        name: server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
